name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '21', '25' ]
        os: [ ubuntu-22.04 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-package: jdk+fx
        java-version: ${{ matrix.java }}

    - name: Build with Maven
      run: mvn install -DskipTests

    - name: Run tests
      run: xvfb-run -a mvn -q verify
